<a href="https://colab.research.google.com/github/niralisaparia99/flask-project/blob/main/Nirali_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

**#### basics**

In [19]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [7]:
b = np.array([[1.0,2.0,3.0],[8.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [8. 5. 6.]]


In [9]:
#get dimension
a.ndim
b.ndim

2

In [11]:
# get shape
a.shape
b.shape # 2 row 3 col

(2, 3)

In [20]:
# get type
a.dtype
#b.dtype

dtype('int16')

In [22]:
# Get size
a.itemsize

2

In [23]:
# Get total size
a.nbytes

6

# **#### accessing/changing specific elements,rows,columns**

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get specific element(12)(r,c)
a[1,4]

12

In [26]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# get specific column
a[:,3]

array([ 4, 11])

In [31]:
# Getting a little more fancy[startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [36]:
a[1,5] = 20
print(a)

a[:,2] = [3]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


# **#### 3-d example**

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
#Get specific element
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [45]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing different types of arrays**

In [57]:
# All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
# All 1s metrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [63]:
# Any other numbers
np.full((2,2), 99)
np.full(a.shape,99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [62]:
# Any other number(full_like)
np.full_like(a,6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [67]:
# Random decimal numbers
np.random.rand(4,3)
np.random.random_sample(a.shape)

array([[0.58160423, 0.15666797, 0.20083652, 0.16709308, 0.35235305,
        0.74826984, 0.44094976],
       [0.35889319, 0.35185032, 0.72491665, 0.98098568, 0.14152169,
        0.27246999, 0.07761712]])

In [73]:
# Random integer value
np.random.randint(4,7, size=(3,3))

array([[4, 6, 5],
       [4, 4, 4],
       [4, 6, 4]])

In [74]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
output = np.ones([5,5])
print(output)

z = np.zeros([3,3])
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [86]:
# Copy an array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


# **mathematics**

In [87]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [88]:
a + 2

array([3, 4, 5, 6])

In [89]:
a - 2

array([-1,  0,  1,  2])

In [90]:
a * 2

array([2, 4, 6, 8])

In [92]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [94]:
b = np.array([1,0,1,0])
print(b)
a + b

[1 0 1 0]


array([2, 2, 4, 4])

In [95]:
a ** 2

array([ 1,  4,  9, 16])

In [97]:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# **linear algebra**

In [100]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [103]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [104]:
# statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
np.min(stats, axis=1)

array([1, 4])

In [111]:
np.max(stats, axis=0)

array([4, 5, 6])

In [112]:
np.sum(stats, axis=0)

array([5, 7, 9])

# **reorganizing array**

In [116]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
# vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [120]:
# Hortizontal stak
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# **Miscellaneous**

# load data from file

In [ ]:
filedata =np.genfromfile('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

# **Boolean masking and advanced indexing**

In [ ]:
filedata[filedata>50]

In [122]:
# you can index with a list in numPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])